### ISSUE TITLE
What is the unit of the value returned by Cpu.getCurrentPower?

### ISSUE THREAD

**Issue by metacosm** [joular/joularjx#41]
Is it mW, W, J, something else?

**Comment by adelnoureddine** [comment]
Hi, the power value is in Watts.

**Comment by metacosm** [comment]
It doesn't appear to be the case, though, as both initial and current power are measured during the same loop iteration meaning that the measurements occur in quick succession. Also, this means that every other Cpu implementations must return 0 for `getInitialPower`, when the Linux RAPL implementation is actually the only one that's supposed to make use of this value.

**Comment by metacosm** [comment]
This also means that the logic / reporting is inconsistent because the agent reports total joules being consumed while in all instances apart from RAPL/Linux, the total is actually Watts, at least, if I understand correctly.

**Comment by adelnoureddine** [comment]
The logic algorithm is:
- on Linux with RAPL, we get an before/after value of energy, and calculate the difference to get the energy consumption
- On RPi and Windows, we only get the power consumption (from formula or Intel API) once, and use it as energy consumption (because our loop is 1 sec, energy = power in this case). Yes ```getInitialPower``` will return 0 in this case, and ```getCurrentPower``` will return power consumption in watts (which for 1 second, is = energy).

The before/after energy collection is done every second, while we collect methods statistics in a smaller sampling loop with the method ```sample()```  https://github.com/joular/joularjx/blob/63f12854f616d60bddd93b9997605e7e920b82b2/src/main/java/org/noureddine/joularjx/monitor/MonitoringHandler.java#L92
Which will loop for the entire second.

Hope this clarifies our approach.
