### ISSUE TITLE
Building JoularJX with Java 8

### ISSUE THREAD

**Issue by anasshatnawi** [joular/joularjx#62]
Hello,

Currently, JoularJX is built on Java 11, limiting its usage to applications developed with Java 11 and above.  To make it compatible with Java 8, it would be important to rebuild JoularJX based on Java 8.

Thanks for your contributions.

Best regards

**Comment by adelnoureddine** [comment]
Oracle's Java 8 premier support has ended in 2022 (with only extended support now), and support by Red Hat for OpenJDK 8 will stop in 2026.
Hence, we will not be pursuing, as part of the main JoularJX project, to support Java 8. 
We will also evaluate, in the coming month, Java 11 support as the premier support by Oracle stopped in 2023, and by Red Hat in 2024 (starting with RHEL 9.5, JDK 17 will be default instead of 11).
